function [R] = ROT( X, Theta)
    switch X
        case {'X','x'} 
               R = [1      0          0      0 ;...
                    0 cos(Theta) -sin(Theta) 0 ;...
                    0 sin(Theta)  cos(Theta) 0 ;...
                    0       0         0      1 ];  
        case {'Y','y'} 
               R = [cos(Theta) 0  sin(Theta) 0 ;...
                      0        1       0     0 ;...
                  -sin(Theta)  0  cos(Theta) 0 ;...
                      0        0       0     1];  
        case {'Z','z'} 
               R = [cos(Theta)  -sin(Theta) 0  0 ;... 
                    sin(Theta)   cos(Theta) 0  0 ;... 
                        0         0         1  0 ;...
                        0         0         0  1 ]; 
   end
end